#!/usr/sbin/nft -f

flush ruleset

table inet filter {

    chain input {
        type filter hook input priority 0;
        policy drop;

        # 1. permitir loopback
        iif lo counter accept

        # 2. permitir conexões já estabelecidas
        ct state established,related counter accept

        # 3. permitir ICMP (ping)
        ip protocol icmp counter accept
        ip6 nexthdr icmpv6 counter accept

        # 4. permitir SSH (opcional, se usares)
        tcp dport 22 counter accept

        # 5. permitir HTTPS (web server)
        tcp dport 443 counter accept

        # 6. permitir VPN
        udp dport 1194 counter accept
    }

    chain forward {
        type filter hook forward priority 0;
        policy drop;
	counter drop;

        ct state established,related accept
    }

    chain output {
        type filter hook output priority 0;
        policy accept;
    }
}
